# Generated by Django 4.0.3 on 2022-12-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_rename_phone_number_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='import_href',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
