# Generated by Django 4.0.3 on 2022-12-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_customer_address_alter_customer_name'),
    ]

    operations = [
        migrations.RenameModel('SalesPerson', 'Employee')
    ]
    atomic = False
