# Generated by Django 4.0.3 on 2022-12-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_update_salesperson_to_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='sales_rest.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automobile', to='sales_rest.automobilevo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='sales_rest.customer'),
        ),
    ]
