# Generated by Django 4.0.3 on 2022-12-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_remove_sale_sales_person_sale_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='import_href',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
