# Generated by Django 4.0.3 on 2022-12-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_sale_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='import_href',
        ),
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto', to='sales_rest.automobilevo'),
        ),
    ]
