# Generated by Django 4.0.3 on 2022-12-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0009_remove_sale_import_href_alter_sale_automobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
    ]
