# Generated by Django 4.0.3 on 2022-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0010_remove_automobilevo_import_href'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number']},
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
