# Generated by Django 4.0.3 on 2022-12-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0011_alter_customer_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
