# Generated by Django 4.0.3 on 2022-12-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0011_alter_automobilevo_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
