# Generated by Django 4.0.3 on 2022-12-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0012_alter_employee_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
    ]
