# Generated by Django 4.0.3 on 2022-12-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_appointment_date_alter_appointment_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=['%Y-%m-%d %H:%M']),
        ),
    ]
